$f=[System.Char]::ConvertFromUtf32(0x1F525);$ch=[System.Char]::ConvertFromUtf32(0x1F4CA);$tg=[System.Char]::ConvertFromUtf32(0x1F3AF);$tr=[System.Char]::ConvertFromUtf32(0x1F4C8);$rb=[System.Char]::ConvertFromUtf32(0x1F916);$bg=[System.Char]::ConvertFromUtf32(0x1F4BC);$gl=[System.Char]::ConvertFromUtf32(0x1F310);$ck=[System.Char]::ConvertFromUtf32(0x2705);$cx=[System.Char]::ConvertFromUtf32(0x274C);$bl=[System.Char]::ConvertFromUtf32(0x26A1);$mn=[System.Char]::ConvertFromUtf32(0x1F4B0);$rk=[System.Char]::ConvertFromUtf32(0x1F680);$bk=[System.Char]::ConvertFromUtf32(0x1F4DA);$sr=[System.Char]::ConvertFromUtf32(0x1F50D);$gm=[System.Char]::ConvertFromUtf32(0x1F48E);$hm=[System.Char]::ConvertFromUtf32(0x1F528);$bx=[System.Char]::ConvertFromUtf32(0x1F4E6);$sc=[System.Char]::ConvertFromUtf32(0x1F5A5);$gc=[System.Char]::ConvertFromUtf32(0x2699);$rp=[System.Char]::ConvertFromUtf32(0x20B9);$tp=[System.Char]::ConvertFromUtf32(0x1F3C6);$pc=[System.Char]::ConvertFromUtf32(0x270F);$lb=[System.Char]::ConvertFromUtf32(0x1F3F7);$pn=[System.Char]::ConvertFromUtf32(0x1F4CC);$up=[System.Char]::ConvertFromUtf32(0x2191);$da=[System.Char]::ConvertFromUtf32(0x2014);$of=[System.Char]::ConvertFromUtf32(0x1F3E2);$ky=[System.Char]::ConvertFromUtf32(0x1F511);$dc=[System.Char]::ConvertFromUtf32(0x1F4C4);$wr=[System.Char]::ConvertFromUtf32(0x270D);$sp=[System.Char]::ConvertFromUtf32(0x2728);$ok=[System.Char]::ConvertFromUtf32(0x1F44D)

$lines = [System.Collections.Generic.List[string]]::new()
function L($s) { $lines.Add($s) }

L('import { useState, useRef, useEffect } from "react";')
L('import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from "recharts";')
L('')
L('const T = {')
L('  bg:"#0a0e27", surface:"#141b3a", card:"#1a2347", border:"#2d3a5f",')
L('  accent:"#ff6b9d", purple:"#c084fc", cyan:"#22d3ee",')
L('  text:"#f0f4ff", muted:"#94a3b8",')
L('  success:"#34d399", warning:"#fbbf24", danger:"#f87171",')
L('  indigo:"#818cf8", teal:"#2dd4bf",')
L('};')
L('')
L("const ROLE_DATA = {")
L("  `"Software Engineer`": {")
L("    color:`"#818cf8`", salary:`"$rp`12$up`45 LPA`", trend:`"+18%`", openings:`"2.4L+`",")
L("    skills:[")
L("      {name:`"JavaScript`",demand:92,yours:72,tag:`"Must Have`"},")
L("      {name:`"React`",demand:88,yours:68,tag:`"Must Have`"},")
L("      {name:`"Node.js`",demand:82,yours:40,tag:`"Important`"},")
L("      {name:`"TypeScript`",demand:78,yours:30,tag:`"Growing`"},")
L("      {name:`"System Design`",demand:75,yours:35,tag:`"Senior`"},")
L("      {name:`"Docker`",demand:68,yours:20,tag:`"DevOps`"},")
L("      {name:`"AWS`",demand:65,yours:15,tag:`"Cloud`"},")
L("      {name:`"GraphQL`",demand:55,yours:10,tag:`"Trending`"},")
L("    ],")
L("    missing:[`"TypeScript`",`"Docker`",`"AWS`",`"GraphQL`"],")
L("    recs:[`"Build 2 full-stack projects with TypeScript`",`"Get AWS Cloud Practitioner cert`",`"Learn Docker basics (1 week)`",`"Add System Design to resume`"],")
L("  },")
L("  `"Product Manager`": {")
L("    color:`"#2dd4bf`", salary:`"$rp`15$up`50 LPA`", trend:`"+22%`", openings:`"85K+`",")
L("    skills:[")
L("      {name:`"Product Strategy`",demand:95,yours:60,tag:`"Core`"},")
L("      {name:`"Data Analysis`",demand:88,yours:50,tag:`"Must Have`"},")
L("      {name:`"Agile/Scrum`",demand:85,yours:70,tag:`"Must Have`"},")
L("      {name:`"SQL`",demand:78,yours:40,tag:`"Important`"},")
L("      {name:`"Figma/UX`",demand:72,yours:55,tag:`"Design`"},")
L("      {name:`"A/B Testing`",demand:68,yours:30,tag:`"Growth`"},")
L("      {name:`"Roadmapping`",demand:90,yours:65,tag:`"Core`"},")
L("      {name:`"Stakeholder Mgmt`",demand:85,yours:60,tag:`"Leadership`"},")
L("    ],")
L("    missing:[`"SQL`",`"A/B Testing`",`"Data Analysis`"],")
L("    recs:[`"Complete Google PM Certificate`",`"Learn SQL (2 weeks)`",`"Build a product case study`",`"Practice A/B testing frameworks`"],")
L("  },")
L("  `"Data Scientist`": {")
L("    color:`"#34d399`", salary:`"$rp`14$up`55 LPA`", trend:`"+35%`", openings:`"1.1L+`",")
L("    skills:[")
L("      {name:`"Python`",demand:96,yours:45,tag:`"Must Have`"},")
L("      {name:`"Machine Learning`",demand:92,yours:30,tag:`"Core`"},")
L("      {name:`"SQL`",demand:88,yours:40,tag:`"Must Have`"},")
L("      {name:`"TensorFlow/PyTorch`",demand:82,yours:20,tag:`"Deep Learning`"},")
L("      {name:`"Statistics`",demand:85,yours:55,tag:`"Foundation`"},")
L("      {name:`"Data Visualization`",demand:75,yours:50,tag:`"Communication`"},")
L("      {name:`"Pandas/NumPy`",demand:90,yours:35,tag:`"Tools`"},")
L("      {name:`"Cloud ML (AWS/GCP)`",demand:70,yours:10,tag:`"Deployment`"},")
L("    ],")
L("    missing:[`"TensorFlow/PyTorch`",`"Cloud ML`",`"Machine Learning`"],")
L("    recs:[`"Complete fast.ai deep learning course`",`"Build 3 Kaggle projects`",`"Get Google Data Analytics cert`",`"Deploy a model on AWS SageMaker`"],")
L("  },")
L("  `"DevOps Engineer`": {")
L("    color:`"#f87171`", salary:`"$rp`16$up`60 LPA`", trend:`"+28%`", openings:`"95K+`",")
L("    skills:[")
L("      {name:`"Docker/Kubernetes`",demand:94,yours:20,tag:`"Must Have`"},")
L("      {name:`"CI/CD Pipelines`",demand:90,yours:30,tag:`"Core`"},")
L("      {name:`"AWS/Azure/GCP`",demand:88,yours:15,tag:`"Cloud`"},")
L("      {name:`"Linux/Shell`",demand:85,yours:50,tag:`"Foundation`"},")
L("      {name:`"Terraform/IaC`",demand:78,yours:10,tag:`"Infrastructure`"},")
L("      {name:`"Monitoring (Grafana)`",demand:72,yours:20,tag:`"Observability`"},")
L("      {name:`"Python/Bash`",demand:80,yours:45,tag:`"Scripting`"},")
L("      {name:`"Security/DevSecOps`",demand:68,yours:15,tag:`"Security`"},")
L("    ],")
L("    missing:[`"Docker/Kubernetes`",`"Terraform/IaC`",`"AWS/Azure/GCP`"],")
L("    recs:[`"Get AWS Solutions Architect cert`",`"Build a Kubernetes cluster project`",`"Learn Terraform (2 weeks)`",`"Set up a full CI/CD pipeline on GitHub Actions`"],")
L("  },")
L("  `"UI/UX Designer`": {")
L("    color:`"#fbbf24`", salary:`"$rp`8$up`35 LPA`", trend:`"+15%`", openings:`"70K+`",")
L("    skills:[")
L("      {name:`"Figma`",demand:96,yours:60,tag:`"Must Have`"},")
L("      {name:`"User Research`",demand:88,yours:50,tag:`"Core`"},")
L("      {name:`"Prototyping`",demand:85,yours:65,tag:`"Must Have`"},")
L("      {name:`"Design Systems`",demand:80,yours:40,tag:`"Scale`"},")
L("      {name:`"CSS/HTML`",demand:72,yours:55,tag:`"Dev Handoff`"},")
L("      {name:`"Motion Design`",demand:65,yours:30,tag:`"Trending`"},")
L("      {name:`"Accessibility`",demand:75,yours:35,tag:`"Standards`"},")
L("      {name:`"Analytics/Heatmaps`",demand:68,yours:25,tag:`"Data-Driven`"},")
L("    ],")
L("    missing:[`"Design Systems`",`"Motion Design`",`"Accessibility`"],")
L("    recs:[`"Build a design system in Figma`",`"Learn Framer Motion basics`",`"Complete Google UX Design cert`",`"Add 3 case studies to portfolio`"],")
L("  },")
L("};")
L("")
L("const TREND_DATA = [")
L("  {month:`"Jul`",jobs:12000,remote:4800},{month:`"Aug`",jobs:14500,remote:5900},")
L("  {month:`"Sep`",jobs:13800,remote:5500},{month:`"Oct`",jobs:16200,remote:6800},")
L("  {month:`"Nov`",jobs:15600,remote:6200},{month:`"Dec`",jobs:18900,remote:8100},")
L("  {month:`"Jan`",jobs:21000,remote:9400},{month:`"Feb`",jobs:23400,remote:10800},")
L("];")
L("")
L("const TOP_SKILLS_2025 = [")
L("  {skill:`"AI/ML`",demand:96,growth:`"+42%`",color:`"#818cf8`"},")
L("  {skill:`"TypeScript`",demand:91,growth:`"+38%`",color:`"#22d3ee`"},")
L("  {skill:`"Kubernetes`",demand:87,growth:`"+31%`",color:`"#34d399`"},")
L("  {skill:`"React`",demand:88,growth:`"+18%`",color:`"#61dafb`"},")
L("  {skill:`"Python`",demand:93,growth:`"+25%`",color:`"#fbbf24`"},")
L("  {skill:`"AWS`",demand:85,growth:`"+22%`",color:`"#f97316`"},")
L("  {skill:`"GraphQL`",demand:72,growth:`"+29%`",color:`"#e879f9`"},")
L("  {skill:`"Rust`",demand:58,growth:`"+55%`",color:`"#f87171`"},")
L("];")

[System.IO.File]::WriteAllText("src/MarketDemand.jsx", ($lines -join "`n"), [System.Text.Encoding]::UTF8)
Write-Host "Data section written OK"
