import { appendFileSync } from "fs";
const p = [];
const a = (s) => p.push(s);

a(``);
a(`export default function MarketDemand({ onNav }) {`);
a(`  const [tab, setTab] = useState("overview");`);
a(`  const [role, setRole] = useState("Software Engineer");`);
a(`  const [hovSkill, setHovSkill] = useState(null);`);
a(`  const rd = ROLE_DATA[role];`);
a(`  const matchPct = Math.round(rd.skills.reduce((acc, s) => acc + Math.min(100, (s.yours / s.demand) * 100), 0) / rd.skills.length);`);
a(`  const missingCount = rd.skills.filter(s => s.yours < s.demand * 0.6).length;`);
a(`  const tabs = [`);
a(`    { k:"overview", label:"Overview" },`);
a(`    { k:"match", label:"Your Match" },`);
a(`    { k:"trends", label:"Trends" },`);
a(`    { k:"recs", label:"AI Recs" },`);
a(`  ];`);
a(`  return (`);
a(`    <div style={{ minHeight:"100vh", background:\`linear-gradient(135deg, \${T.bg} 0%, #0f1535 50%, \${T.bg} 100%)\`, padding:"0 0 60px" }}>`);
a(``);
a(`      {/* HERO */}`);
a(`      <div style={{ position:"relative", overflow:"hidden", padding:"40px 0 32px", marginBottom:8 }}>`);
a(`        <div style={{ position:"absolute", top:-60, left:"10%", width:400, height:400, background:\`radial-gradient(circle, \${T.accent}18, transparent 70%)\`, borderRadius:"50%", filter:"blur(60px)", pointerEvents:"none" }}/>`);
a(`        <div style={{ position:"absolute", top:-40, right:"15%", width:350, height:350, background:\`radial-gradient(circle, \${T.purple}18, transparent 70%)\`, borderRadius:"50%", filter:"blur(60px)", pointerEvents:"none" }}/>`);
a(`        <div style={{ position:"relative", zIndex:1 }}>`);
a(`          <div style={{ display:"inline-flex", alignItems:"center", gap:8, background:"rgba(255,107,157,0.12)", border:"1px solid rgba(255,107,157,0.3)", borderRadius:20, padding:"5px 14px", marginBottom:16, fontSize:11, color:T.accent, fontWeight:700, letterSpacing:1 }}>`);
a(`            <span style={{ width:6, height:6, background:T.accent, borderRadius:"50%", display:"inline-block" }}/>`);
a(`            LIVE MARKET DATA — 2025`);
a(`          </div>`);
a(`          <h1 style={{ fontFamily:"Space Grotesk,sans-serif", fontSize:"clamp(26px,4vw,38px)", fontWeight:800, color:T.text, marginBottom:8, lineHeight:1.2 }}>`);
a(`            Market Demand{" "}`);
a(`            <span style={{ background:\`linear-gradient(135deg, \${T.accent}, \${T.purple})\`, WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>Intelligence</span>`);
a(`          </h1>`);
a(`          <p style={{ color:T.muted, fontSize:15, lineHeight:1.6, maxWidth:520 }}>Real-time skill demand data, salary benchmarks, and AI-powered career recommendations.</p>`);
a(`        </div>`);
a(`      </div>`);
a(``);
a(`      {/* KPI STRIP */}`);
a(`      <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:16, marginBottom:28 }}>`);
a(`        {[`);
a(`          { label:"Open Positions", val:240000, suffix:"+", color:T.indigo, icon:"??", sub:"Tech sector India" },`);
a(`          { label:"Avg Salary Hike", val:28, suffix:"%", color:T.success, icon:"??", sub:"YoY for skilled devs" },`);
a(`          { label:"Remote Jobs", val:46, suffix:"%", color:T.cyan, icon:"??", sub:"Of all tech openings" },`);
a(`          { label:"Skills Gap", val:missingCount, suffix:" gaps", color:T.warning, icon:"??", sub:\`In \${role}\` },`);
a(`        ].map((k, i) => (`);
a(`          <GlowCard key={i} color={k.color} style={{ padding:"20px 22px" }}>`);
a(`            <div style={{ display:"flex", alignItems:"flex-start", justifyContent:"space-between", marginBottom:10 }}>`);
a(`              <span style={{ fontSize:24 }}>{k.icon}</span>`);
a(`              <span style={{ fontSize:10, color:k.color, fontWeight:700, background:\`\${k.color}18\`, padding:"3px 8px", borderRadius:10 }}>LIVE</span>`);
a(`            </div>`);
a(`            <div style={{ fontFamily:"Space Grotesk,sans-serif", fontSize:28, fontWeight:800, color:k.color, lineHeight:1 }}>`);
a(`              <AnimCounter target={k.val} suffix={k.suffix}/>`);
a(`            </div>`);
a(`            <div style={{ fontSize:12, fontWeight:700, color:T.text, marginTop:4 }}>{k.label}</div>`);
a(`            <div style={{ fontSize:11, color:T.muted, marginTop:2 }}>{k.sub}</div>`);
a(`          </GlowCard>`);
a(`        ))}`);
a(`      </div>`);
a(``);
a(`      {/* ROLE SELECTOR */}`);
a(`      <GlowCard color={rd.color} style={{ marginBottom:24, padding:"18px 22px" }} hover={false}>`);
a(`        <div style={{ display:"flex", alignItems:"center", gap:16, flexWrap:"wrap" }}>`);
a(`          <div style={{ flex:1, minWidth:200 }}>`);
a(`            <div style={{ fontSize:11, color:T.muted, fontWeight:700, marginBottom:6, letterSpacing:1 }}>ANALYZING ROLE</div>`);
a(`            <select value={role} onChange={e => setRole(e.target.value)}`);
a(`              style={{ background:T.surface, border:\`1px solid \${rd.color}66\`, borderRadius:12, padding:"10px 16px", color:T.text, fontSize:15, fontWeight:700, fontFamily:"Space Grotesk,sans-serif", outline:"none", cursor:"pointer", width:"100%", maxWidth:320 }}>`);
a(`              {Object.keys(ROLE_DATA).map(r => <option key={r} value={r} style={{ background:T.card }}>{r}</option>)}`);
a(`            </select>`);
a(`          </div>`);
a(`          <div style={{ display:"flex", gap:20, flexWrap:"wrap" }}>`);
a(`            {[`);
a(`              { label:"Avg Salary", val:rd.salary, icon:"??" },`);
a(`              { label:"Hiring Trend", val:rd.trend, icon:"??" },`);
a(`              { label:"Open Roles", val:rd.openings, icon:"??" },`);
a(`            ].map((s, i) => (`);
a(`              <div key={i} style={{ textAlign:"center" }}>`);
a(`                <div style={{ fontSize:20 }}>{s.icon}</div>`);
a(`                <div style={{ fontFamily:"Space Grotesk,sans-serif", fontSize:16, fontWeight:800, color:rd.color }}>{s.val}</div>`);
a(`                <div style={{ fontSize:11, color:T.muted }}>{s.label}</div>`);
a(`              </div>`);
a(`            ))}`);
a(`          </div>`);
a(`          <MatchRing pct={matchPct} color={rd.color} size={100}/>`);
a(`        </div>`);
a(`      </GlowCard>`);
a(``);
a(`      {/* TABS */}`);
a(`      <div style={{ display:"flex", gap:8, marginBottom:24, flexWrap:"wrap" }}>`);
a(`        {tabs.map(t => (`);
a(`          <button key={t.k} onClick={() => setTab(t.k)}`);
a(`            style={{ padding:"10px 20px", borderRadius:12, border:\`1px solid \${tab===t.k ? rd.color : T.border}\`, background: tab===t.k ? \`\${rd.color}18\` : "transparent", color: tab===t.k ? rd.color : T.muted, cursor:"pointer", fontSize:13, fontWeight:700, transition:"all 0.2s", fontFamily:"Space Grotesk,sans-serif", boxShadow: tab===t.k ? \`0 0 20px \${rd.color}30\` : "none" }}>`);
a(`            {t.label}`);
a(`          </button>`);
a(`        ))}`);
a(`      </div>`);

appendFileSync("src/MarketDemand.jsx", p.join("\n"));
console.log("Part 3 done: " + p.length + " lines");
